<?php

/**
 * @file
 */

/**
 *
 */
function wheather_theme() {
  return [
    WheatherBlock => [
      'variables' => [
        'titles' => NULL,
        'description' => NULL,
        'temp_minimum' => NULL,
        'temp_maximum' => NULL,
        'pressure' => NULL,
        'humidity' => NULL,
        'wind' => NULL,
        'image' => NULL,
      ],
      'template' => 'WheatherBlock',
    ],
  ];
}
